// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN8txBtXo0lnsziARvN5TQ3kA-KlG8nIY',
    appId: '1:153671556393:web:95cfd5466537462eaf6b38',
    messagingSenderId: '153671556393',
    projectId: 'the-red-thread-2',
    authDomain: 'the-red-thread-2.firebaseapp.com',
    storageBucket: 'the-red-thread-2.firebasestorage.app',
    measurementId: 'G-6QQRZCF1V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2lAtaA0MODv61ulSLTVhOGxrsSMeZvs',
    appId: '1:153671556393:android:2f8da1ee8dde310eaf6b38',
    messagingSenderId: '153671556393',
    projectId: 'the-red-thread-2',
    storageBucket: 'the-red-thread-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwwrQs_Z0it0lV2r4vOTyNF_WM1WaGIh4',
    appId: '1:153671556393:ios:8957596d1ba3d908af6b38',
    messagingSenderId: '153671556393',
    projectId: 'the-red-thread-2',
    storageBucket: 'the-red-thread-2.firebasestorage.app',
    iosBundleId: 'com.example.theReadThread',
  );

}